/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-04-10 07:13:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import ex01.*;
import java.util.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>게시판 목록</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"home.css\"/>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t.tab{width:700px; margin:auto;}\r\n");
      out.write("\t\t.tab td{border:2px solid red; text-align:center; margin:auto;}\r\n");
      out.write("\t\t.tab .title{background:white; color:black;}\r\n");
      out.write("\t\t.tab .data:nth-child(2n+1){background:gray;}\r\n");
      out.write("\t\t.tab .data:hover{background:skyblue; color:white;}\r\n");
      out.write("\t\t#content a{text-align:center;}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"page\">\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<h1>게시판 목록</h1>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<a href=\"insert.html\" style=\"float:right; margin-right:30px; font-size:15px;\">글 쓰기</a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<table class=\"tab\">\r\n");
      out.write("\t\t\t\t<tr class=\"title\">\r\n");
      out.write("\t\t\t\t\t<td width=30>No</td>\r\n");
      out.write("\t\t\t\t\t<td>Title</td>\r\n");
      out.write("\t\t\t\t\t<td width=150>Date</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");

					BoardDAO dao=new BoardDAO();
					ArrayList<BoardVO> list=dao.list();
					for(int i=0; i<list.size(); i++) {
						BoardVO vo=new BoardVO();
						vo=list.get(i);
						int bnum=vo.getBnum();
						String title=vo.getTitle();
						SimpleDateFormat sdf=new SimpleDateFormat("yyyy년 MM월 dd일 hh:mm:ss");
						String date=sdf.format(vo.getWdate());
						out.print("<tr class='data'>");
						out.print("<td>" + bnum + "</td>");
						out.print("<td><a href='read.jsp?bnum=" + bnum + "'>" + title + "</a></td>");
						out.print("<td>" + date + "</td>");
						out.print("</tr>");
					}
				
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
