/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-04-12 06:09:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ex01.*;
import java.util.*;
import java.text.*;

public final class read_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String strBnum=request.getParameter("bnum");
	int bnum=Integer.parseInt(strBnum);
	
	BoardDAO dao=new BoardDAO();
	BoardVO vo=dao.read(bnum);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>글 읽기</title>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t*{font-family:'Times New Roman'}\r\n");
      out.write("\t\tbody{background:gray;}\r\n");
      out.write("\t\t#page{background:black; color:white; width:1000px; margin:auto; padding:10px;\r\n");
      out.write("\t\t\tbox-shadow:10px 10px 10px #ffffb0; border-radius:10px 10px 10px 10px;}\r\n");
      out.write("\t\t#content{width:900px; padding:10px; border:1px solid white;\r\n");
      out.write("\t\t\t\tmargin:20px auto;}\r\n");
      out.write("\t\t#content h1{text-align:center;}\r\n");
      out.write("\t\t#menu{width:700px; margin:auto;}\r\n");
      out.write("\t\ta{color:white; font-size:20px;}\r\n");
      out.write("\t\ta:hover{background:black; color:white;}\r\n");
      out.write("\t\t.tabInsert{width:700px; background:gray; margin:20px auto; border-radius:5px 5px 5px 5px; padding:5px;}\r\n");
      out.write("\t\t.button{width:50px; height:30px; margin-right:10px;}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"page\">\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<h1>글 읽기</h1>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<div id=\"menu\">\r\n");
      out.write("\t\t\t\t<a href=\"list.jsp\">목록</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<form class=\"form\" action=\"sqlUpdate.jsp\">\r\n");
      out.write("\t\t\t\t<table class=\"tabInsert\">\r\n");
      out.write("\t\t\t\t\t<tr class=\"title\">\r\n");
      out.write("\t\t\t\t\t\t<td>글 제목</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" size=78 name=\"title\" value=\"");
      out.print(vo.getTitle());
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>글 내용</td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=2>\r\n");
      out.write("\t\t\t\t\t\t<textarea rows=\"10\" cols=\"80\" name=\"content\">");
      out.print(vo.getContent());
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div style=\"text-align:right; margin-right:100px;\">\r\n");
      out.write("\t\t\t\t\t<input class=\"button\" type=\"submit\" value=\"수정\">\r\n");
      out.write("\t\t\t\t\t<input class=\"button\" type=\"button\" value=\"삭제\">\r\n");
      out.write("\t\t\t\t\t<input class=\"button\" type=\"reset\" value=\"취소\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
