/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-05-06 03:57:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.course;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ex01.*;
import java.util.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>강좌목록</title>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t#ctab{text-align:center; width:700px;}\r\n");
      out.write("\t\t#tab1{text-align:center; width:700px;}\r\n");
      out.write("\t\t.title{background:yellow;}\r\n");
      out.write("\t\t.row:hover{background:black; color:white;}\r\n");
      out.write("\t\tbutton{cursor:pointer;}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"menu\">\r\n");
      out.write("\t\t<a href=\"../professor/list.jsp\">교수관리</a>\r\n");
      out.write("\t\t<a href=\"../course/list.jsp\">강좌관리</a>\r\n");
      out.write("\t\t<a href=\"../student/list.jsp\">학생관리</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<h1>[강좌목록]</h1>\r\n");
      out.write("\t<table id=\"ctab\" border=1>\r\n");
      out.write("\t\t<tr class=\"title\">\r\n");
      out.write("\t\t\t<td>강좌번호</td>\r\n");
      out.write("\t\t\t<td>강좌이름</td>\r\n");
      out.write("\t\t\t<td>강의시간수</td>\r\n");
      out.write("\t\t\t<td>강의실</td>\r\n");
      out.write("\t\t\t<td>최대수강 인원수</td>\r\n");
      out.write("\t\t\t<td>수강신청 인원수</td>\r\n");
      out.write("\t\t\t<td>성적입력</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");

			CDAO cdao=new CDAO();
			ArrayList<CVO> array=cdao.list("%%");
			for(CVO vo:array){
				out.print("<tr class='row'>");
				out.print("<td class='lcode'>"+vo.getLcode()+"</td>");
				out.print("<td class='lname'>"+vo.getLname()+"</td>");
				out.print("<td class='hours'>"+vo.getHours()+"</td>");
				out.print("<td>"+vo.getRoom()+"</td>");
				out.print("<td>"+vo.getCapacity()+"</td>");
				out.print("<td>"+vo.getPersons()+"</td>");
				out.print("<td><button>성적입력</button></td>");
				out.print("</tr>");
			}
		
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"student\" style=\"display:none\">\r\n");
      out.write("\t\t<h1>[학생 성적입력]</h1>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t강좌번호 : <span id=\"lcode\"></span>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t강좌이름 : <span id=\"lname\"></span>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t강의시간 : <span id=\"hours\"></span><br>\t\r\n");
      out.write("\t\t\t<button id=\"btnSave\">전체저장</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<table id=\"tab1\" border=1></table>\r\n");
      out.write("\t<script id=\"temp1\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t\t\t<tr class=\"title\">\r\n");
      out.write("\t\t\t\t<td><input type=\"checkbox\" id=\"checkAll\"></td>\r\n");
      out.write("\t\t\t\t<td>학생이름</td>\r\n");
      out.write("\t\t\t\t<td>학생번호</td>\r\n");
      out.write("\t\t\t\t<td>점수</td>\r\n");
      out.write("\t\t\t\t<td>저장</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t{{#each sarray}}\r\n");
      out.write("\t\t\t<tr class=\"row1\">\r\n");
      out.write("\t\t\t\t<td><input type=\"checkbox\" class=\"check\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"sname\">{{sname}}</td>\r\n");
      out.write("\t\t\t\t<td class=\"scode\">{{scode}}</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" class=\"grade\" value=\"{{grade}}\"></td>\r\n");
      out.write("\t\t\t\t<td><button>저장</button></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t{{/each}}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar lcode;\r\n");
      out.write("\tvar lname;\r\n");
      out.write("\tvar hours;\r\n");
      out.write("\r\n");
      out.write("\t$(\"#ctab\").on(\"click\", \".row button\", function(){\r\n");
      out.write("\t\tvar row=$(this).parent().parent();\r\n");
      out.write("\t\tlcode=row.find(\".lcode\").html();\r\n");
      out.write("\t\tlname=row.find(\".lname\").html();\r\n");
      out.write("\t\thours=row.find(\".hours\").html();\r\n");
      out.write("\t\t$(\"#lcode\").html(lcode);\r\n");
      out.write("\t\t$(\"#lname\").html(lname);\r\n");
      out.write("\t\t$(\"#hours\").html(hours);\r\n");
      out.write("\t\t$(\"#student\").show();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tgetList();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getList(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\turl:\"sjson.jsp\",\r\n");
      out.write("\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\tdata:{\"lcode\":lcode},\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tvar temp=Handlebars.compile($(\"#temp1\").html());\r\n");
      out.write("\t\t\t\t$(\"#tab1\").html(temp(data));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//체크박스모두표시\r\n");
      out.write("\t$(\"#tab1\").on(\"click\", \"#checkAll\", function(){\r\n");
      out.write("\t\tif($(this).is(\":checked\")){\r\n");
      out.write("\t\t\t$(\"#tab1 .row1 .check\").each(function(){\r\n");
      out.write("\t\t\t\t$(this).prop(\"checked\", true);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\t$(\"#tab1 .row1 .check\").each(function(){\r\n");
      out.write("\t\t\t\t$(this).prop(\"checked\", false);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//성적수정후 저장\r\n");
      out.write("\t$(\"#tab1\").on(\"click\", \".row1 button\", function(){\r\n");
      out.write("\t\tif(!confirm(\"수정하시겠습니까?\")) return;\r\n");
      out.write("\t\tvar row1=$(this).parent().parent();\r\n");
      out.write("\t\tvar grade=row1.find(\".grade\").val();\r\n");
      out.write("\t\tvar scode=row1.find(\".scode\").html();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\turl:\"update.jsp\",\r\n");
      out.write("\t\t\tdata:{\"grade\":grade, \"scode\":scode, \"lcode\":lcode},\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tvar temp=Handlebars.compile($(\"#temp1\").html());\r\n");
      out.write("\t\t\t\t$(\"#tab1\").html(temp(data));\r\n");
      out.write("\t\t\t\talert(\"수정이 완료되었습니다.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tgetList();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//체크박스 선택된 값 모두저장\r\n");
      out.write("\t$(\"#btnSave\").on(\"click\", function(){\r\n");
      out.write("\t\tif(!confirm(\"선택한 학생의 점수를 수정하시겠습니까?\")) return;\r\n");
      out.write("\t\t$(\"#tab1 .row1 .check:checked\").each(function(){\r\n");
      out.write("\t\t\trow1=$(this).parent().parent();\r\n");
      out.write("\t\t\tgrade=row1.find(\".grade\").val();\r\n");
      out.write("\t\t\tscode=row1.find(\".scode\").html();\r\n");
      out.write("\t\t\t$(this).prop(\"checked\", false);\r\n");
      out.write("\t\t\t$(\"#tab1 #checkAll\").prop(\"checked\", false);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\t\turl:\"update.jsp\",\r\n");
      out.write("\t\t\t\tdata:{\"grade\":grade, \"scode\":scode, \"lcode\":lcode},\r\n");
      out.write("\t\t\t\tsuccess:function(data){}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\talert(\"수정이 완료되었습니다.\");\r\n");
      out.write("\t\tgetList();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
