/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-04-20 00:17:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ex01.*;
import java.util.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>댓글 관리</title>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t#page{padding:20px;width:800px;background:gray; color:yellow; margin:auto;}\r\n");
      out.write("\t\t#page input{text-align:center; margin:auto;}\r\n");
      out.write("\t\th1{margin:auto; text-align:center;}\r\n");
      out.write("\t\t.box{width:700px; border:1px dotted black; padding:10px; margin:10px auto;}\r\n");
      out.write("\t\t.title{overflow:hidden;}\r\n");
      out.write("\t\t.date{ font-size:20px; color:orange; width:200px;float:left;}\r\n");
      out.write("\t\t.like{float:right;}\r\n");
      out.write("\t\t.cnt{font-size:12px; color:pink;}\r\n");
      out.write("\t\t.content{background:red; padding:20px; font-size:15px;}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"page\">\r\n");
      out.write("\t\t<h1>[댓글 관리]</h1>\r\n");
      out.write("\t\t<input type=\"text\" id=\"content\" size=100>\r\n");
      out.write("\t\t<input type=\"button\" value=\"저장\" id=\"btnInsert\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t<div class=\"title\">\r\n");
      out.write("\t\t\t\t<div class=\"date\">오늘날짜</div>\r\n");
      out.write("\t\t\t\t<div class=\"like\">\r\n");
      out.write("\t\t\t\t\t<button class=\"update\">좋아요+1</button>\r\n");
      out.write("\t\t\t\t\t<span class=\"cnt\">좋아요수</span><br>\r\n");
      out.write("\t\t\t\t\t<button class=\"delete\">삭제</button><br><br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"content\">내용!!</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");

			ReplyDAO dao=new ReplyDAO();
			ArrayList<ReplyVO> array=dao.list();
			for(int i=0; i<array.size(); i++){
				ReplyVO vo=array.get(i);
				int rnum=vo.getRnum();
				String content=vo.getContent();
				Date wdate=vo.getWdate();
				int cnt=vo.getCnt();
				out.print("<div class='box'>");
				out.print("<div class='title'>");
				out.print("<div class='date'>" + wdate + "</div>");
				out.print("<div class='like' rnum=" + rnum + ">");
				out.print("<button class='update'>♣</button>");
				out.print("<span class='cnt'>" + cnt + "</span><br>");
				out.print("<button class='delete'>삭제</button>");
				out.print("</div>");
				out.print("</div>");
				out.print("<div class='content'>" + content + "</div>");
				out.print("</div>");
			}
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t//행에 있는 삭제버튼을 클릭했을 때\r\n");
      out.write("\t$(\".box\").on(\"click\", \".delete\", function(){\r\n");
      out.write("\t\tvar rnum=$(this).parent().attr(\"rnum\");\r\n");
      out.write("\t\tif(!confirm(rnum+\"번을 삭제 하시겠습니까?\")) return;\r\n");
      out.write("\t\tlocation.href=\"sqlDelete.jsp?rnum=\"+rnum;\r\n");
      out.write("\t});\r\n");
      out.write("\t//등록버튼 클릭 했을 때\r\n");
      out.write("\t$(\"#btnInsert\").on(\"click\", function(){\r\n");
      out.write("\t\tif(!confirm(\"저장하시겠습니까?\")) return;\r\n");
      out.write("\t\tvar content=$(\"#content\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tlocation.href=\"sqlInsert.jsp?content=\"+content;\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//좋아요수 늘리기\r\n");
      out.write("\t$(\".box\").on(\"click\", \".update\", function(){\r\n");
      out.write("\t\tvar rnum=$(this).parent().attr(\"rnum\");\r\n");
      out.write("\t\tlocation.href=\"sqlUpdate.jsp?rnum=\"+rnum;\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
