/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-05-01 07:42:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.student;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ex01.*;
import java.util.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>학생목록</title>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t#stab{text-align:center;}\r\n");
      out.write("\t\t#tab2{text-align:center; width:700px;}\r\n");
      out.write("\t\t.title{background:yellow;}\r\n");
      out.write("\t\t.row:hover{background:black; color:white;}\r\n");
      out.write("\t\tbutton{cursor:pointer;}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"menu\">\r\n");
      out.write("\t\t<a href=\"../professor/list.jsp\">교수관리</a>\r\n");
      out.write("\t\t<a href=\"../course/list.jsp\">강좌관리</a>\r\n");
      out.write("\t\t<a href=\"../student/list.jsp\">학생관리</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<h1>[학생목록]</h1>\r\n");
      out.write("\t<table id=\"stab\" border=1>\r\n");
      out.write("\t\t<tr class=\"title\">\r\n");
      out.write("\t\t\t<td>학생이름</td>\r\n");
      out.write("\t\t\t<td>학생번호</td>\r\n");
      out.write("\t\t\t<td>소속학과</td>\r\n");
      out.write("\t\t\t<td>생년월일</td>\r\n");
      out.write("\t\t\t<td>지도교수번호</td>\r\n");
      out.write("\t\t\t<td>수강신청</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");

			SDAO sdao=new SDAO();
			ArrayList<SVO> array=sdao.list("%%");
			for(SVO vo:array){
				out.print("<tr class='row'>");
				out.print("<td class='sname'>" + vo.getSname() + "</td>");
				out.print("<td class='scode'>" + vo.getScode() + "</td>");
				out.print("<td>" + vo.getDept() + "</td>");
				out.print("<td>" + vo.getBirthday() + "</td>");
				out.print("<td>" + vo.getAdvisor() + "</td>");
				out.print("<td><button>수강신청</button></td>");
				out.print("</tr>");
			}
		
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"enrollment\" style=\"display:none\">\r\n");
      out.write("\t\t<h1>[수강신청목록]</h1>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t이름 : <span id=\"sname\"></span>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t학번 : <span id=\"scode\"></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t강좌명 :\r\n");
      out.write("\t\t<select id=\"lcode\"></select>\r\n");
      out.write("\t\t<script id=\"temp1\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t\t{{#each carray}}\r\n");
      out.write("\t\t\t<option value={{lcode}}>{{lcode}} : {{lname}}</option>\r\n");
      out.write("\t\t{{/each}}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<input type=\"button\" value=\"신청\" id=\"btnInsert\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<table id=\"tab2\" border=1></table>\r\n");
      out.write("\t<script id=\"temp2\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t\t\t<tr class=\"header\">\r\n");
      out.write("\t\t\t\t<td>강좌번호</td>\r\n");
      out.write("\t\t\t\t<td>강좌이름</td>\r\n");
      out.write("\t\t\t\t<td>수강신청일</td>\r\n");
      out.write("\t\t\t\t<td>점수</td>\r\n");
      out.write("\t\t\t\t<td>수강취소</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t{{#each earray}}\r\n");
      out.write("\t\t\t<tr class=\"row2\">\r\n");
      out.write("\t\t\t\t<td class=\"lcode\">{{lcode}}</td>\r\n");
      out.write("\t\t\t\t<td class=\"lname\">{{lname}}</td>\r\n");
      out.write("\t\t\t\t<td>{{edate}}</td>\r\n");
      out.write("\t\t\t\t<td>{{grade}}</td>\r\n");
      out.write("\t\t\t\t<td><button>수강취소</button></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t{{/each}}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar scode;\r\n");
      out.write("\tvar lcode;\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t//수강신청목록출력\r\n");
      out.write("\tfunction getList(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\turl:\"ejson.jsp\",\r\n");
      out.write("\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\tdata:{\"scode\":scode},\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tvar temp=Handlebars.compile($(\"#temp2\").html());\r\n");
      out.write("\t\t\t\t$(\"#tab2\").html(temp(data));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//수강신청 버튼을 클릭했을 때 목록출력\r\n");
      out.write("\t$(\"#stab\").on(\"click\", \".row button\", function(){\r\n");
      out.write("\t\tvar row=$(this).parent().parent();\r\n");
      out.write("\t\tvar sname=row.find(\".sname\").html();\r\n");
      out.write("\t\t$(\"#sname\").html(sname);\r\n");
      out.write("\t\tscode=row.find(\".scode\").html();\r\n");
      out.write("\t\t$(\"#scode\").html(scode);\r\n");
      out.write("\t\t$(\"#enrollment\").show();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tgetList();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//담당교수의 강좌 목록출력\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"get\",\r\n");
      out.write("\t\turl:\"cjson.jsp\",\r\n");
      out.write("\t\tdataType:\"json\",\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\tvar temp=Handlebars.compile($(\"#temp1\").html());\r\n");
      out.write("\t\t\t$(\"#lcode\").html(temp(data));\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//수강신청\r\n");
      out.write("\t$(\"#btnInsert\").on(\"click\", function(){\r\n");
      out.write("\t\tif(!confirm(\"수강신청을 하시겠습니까?\")) return;\r\n");
      out.write("\t\tlcode=$(\"#lcode\").val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\turl:\"insert.jsp\",\r\n");
      out.write("\t\t\tdata:{\"lcode\":lcode, \"scode\":scode},\r\n");
      out.write("\t\t\tsuccess:function(){\r\n");
      out.write("\t\t\t\talert(\"수강신청됐지롱\");\r\n");
      out.write("\t\t\t\tgetList();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//수강신청취소\r\n");
      out.write("\t$(\"#tab2\").on(\"click\", \".row2 button\",function(){\r\n");
      out.write("\t\tif(!confirm(\"수강신청을 취소 하시겠습니까?\")) return;\r\n");
      out.write("\t\tlcode=$(\"#lcode\").val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\turl:\"delete.jsp\",\r\n");
      out.write("\t\t\tdata:{\"lcode\":lcode, \"scode\":scode},\r\n");
      out.write("\t\t\tsuccess:function(){\r\n");
      out.write("\t\t\t\talert(\"수강취소됐지롱\");\r\n");
      out.write("\t\t\t\tgetList();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
